/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AgenticPaymentsInterface extends Interface {
    getFunction(nameOrSignature: "agents" | "makePayment" | "owner" | "registerAgent" | "revokeAgent"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentMade"): EventFragment;

    encodeFunctionData(functionFragment: 'agents', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'makePayment', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerAgent', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeAgent', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'agents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'makePayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeAgent', data: BytesLike): Result;
  }

  
    export namespace PaymentMadeEvent {
      export type InputTuple = [agent: AddressLike, merchant: AddressLike, amount: BigNumberish];
      export type OutputTuple = [agent: string, merchant: string, amount: bigint];
      export interface OutputObject {agent: string, merchant: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgenticPayments extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgenticPayments;
    waitForDeployment(): Promise<this>;

    interface: AgenticPaymentsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    agents: TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, bigint, bigint] & {authorized: boolean, spendingLimit: bigint, spent: bigint }],
      'view'
    >
    

    
    makePayment: TypedContractMethod<
      [merchant: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerAgent: TypedContractMethod<
      [agent: AddressLike, spendingLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeAgent: TypedContractMethod<
      [agent: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'agents'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, bigint, bigint] & {authorized: boolean, spendingLimit: bigint, spent: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'makePayment'): TypedContractMethod<
      [merchant: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerAgent'): TypedContractMethod<
      [agent: AddressLike, spendingLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeAgent'): TypedContractMethod<
      [agent: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'PaymentMade'): TypedContractEvent<PaymentMadeEvent.InputTuple, PaymentMadeEvent.OutputTuple, PaymentMadeEvent.OutputObject>;

    filters: {
      
      'PaymentMade(address,address,uint256)': TypedContractEvent<PaymentMadeEvent.InputTuple, PaymentMadeEvent.OutputTuple, PaymentMadeEvent.OutputObject>;
      PaymentMade: TypedContractEvent<PaymentMadeEvent.InputTuple, PaymentMadeEvent.OutputTuple, PaymentMadeEvent.OutputObject>;
    
    };
  }